version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /application
    ports:
      - 3000:3000
    volumes:
      - .:/application
      - draw-contest_node_modules:/application/node_modules
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15.2-alpine
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - .local/init/postgres:/docker-entrypoint-initdb.d
      - .local/data/postgres:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 20s
      timeout: 20s
      retries: 5

volumes:
  draw-contest_node_modules:
